version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: loanApplicationportal_mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rxoot


      MYSQL_DATABASE: LoanApplicationPortalApp
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local
